.github/pull_request_template.md
.husky/pre-commit
package-lock.json
package.json
src/example/ExamplePage.jsx
src/index.jsx
webpack.dev.config.js

Added a Pull Request template, this will pre-fill the PR descriptions when creating a new one.
Also added automated code linting and formatting on commit.
```diff
```

chore(DEX-3916): Add PR template, automate code formatting and linting

---

src/header/Header.scss
src/header/MobileHeader.jsx
src/header/MobileMenu.jsx

Include styles for hamburger menu from openedx frontend-component-header
Move mobile menu to the left side of the header
Move logo to the right side of the header
Decrease menu size
```diff
```

fix(DEX-3924): Include mobile hamburger menu style

---

jest.config.js
package-lock.json
package.json
public/index.html
src/features/course-player/CoursePlayer.jsx
src/features/course-player/CoursePlayer.test.jsx
src/features/course-player/sequence-container/SequenceContainer.scss
src/features/course-player/sequence-container/SequenceContainer.test.jsx
src/features/course-view/CourseView.test.jsx
src/features/layout/Layout.test.jsx
src/i18n/index.js
src/index.jsx
src/setupTest.js
webpack.test.config.js

This makes the course content fully functional.
- Added Helmet for managing browser tab title, set it with the course name
- Fix styling on small screens for course content
- Added tests for course content
- Added testing tools for testing with styles and mocks from frontend-app-learning
- Import i18n app translations for course content form frontend-app-learning
```diff
```

feat(DEX-3929): Importing and integrating course content

---

src/features/course-player/sequence-container/SequenceContainer.scss

- Remove underline for course title
- Apply course navigation buttons styles according to latest UI/UX discussions
Please note: the "next" button will probably look weird and with a red color, because we don't have the custom branding applied in this repo. It looks good with the custom branding.
```diff
```

style(DEX-4048): Course content styles

---

src/features/course-player/sequence-container/SequenceContainer.scss

Adding button font & weight to match course content
```diff
```

fix(DEX-4013)

---

webpack.prod.config.js

Production build was failing, needed to add module alias like in dev.
```diff
```

fix(DEX-3779): Add webpack config for prod with necessary fixes

---

src/features/course-view/CourseView.scss
src/features/footer/Footer.scss
src/features/header/Header.scss
src/variables.scss

Some elements of the sidebar were hidden by the footer when they were expanded, also I'm using this PR to upload adjustment of footer and header dimensions, color, etc.
```diff
```

fix(DEX-4086): some elements of sidebar are hidden by the footer

---

src/features/course-player/sequence-container/SequenceContainer.scss

We are removing the previous and next button styles and will style in the brand packages's overrides.scss.
This is for compatibility with Academy style
```diff
```

Fix(remove nav button style)

---

src/features/course-player/CoursePlayer.scss
src/features/course-view/CourseView.scss
src/features/footer/Footer.scss
src/features/header/Header.scss
src/features/layout/Layout.scss

Changed mobile breakpoint to xl (1200px)
```diff
```

fix(DEX-4162): Changed mobile breakpoint to xl (1200px)

---

src/components/Section/Section.jsx
src/components/Sequence/Sequence.jsx
src/components/Unit/Unit.jsx
src/features/course-view/CourseView.jsx
src/features/course-view/CourseView.scss
src/features/sidebar/Sidebar.jsx

This PR includes: 
Hide and Unhide vertical sidebar, design team still trying things so this is some kind of alpha so they can try it and see how it looks. 
Current page location flag on section and sequence when is collapsed. 
Some hot fixes.
```diff
```

feat(DEX-4079,DEX-4167): hide-unhide sidebar, location flag on section and sequence and some hotfixes.

---

src/features/header/Header.jsx
src/features/header/Header.scss
src/features/header/Header.test.jsx

https://projects.wgu.edu/browse/DEX-4164
- Remove course number from header.
- Update unit test to remove check for course number.
- Fix margin between left side and logo + logo and title. Will now match dimensions in Figma.
- Fix mobile header style. Padding is the same on the logo and menu for consistency and so the title is aligned in the center.
```diff
```

feat(dex 4164)

---

src/features/course-view/CourseView.scss

I updated the colors adding variables instead of static colors.
```diff
```

refactor(DEX-4094): adding variables instead of static colors.

---

docs/how_tos/paragon-elements.md
src/features/course-player/CoursePlayer.scss
src/features/footer/Footer.scss
src/index.scss
src/variables.scss

https://projects.wgu.edu/browse/DEX-4221
Update MFE elements to utilize Paragon color variables.
Update footer background to a non utilized color.
```diff
```

feat(DEX-4221)

---

src/features/course-view/CourseView.scss

The units have hover now.
```diff
```

refactor(DEX-4206): unit hover color

---

src/features/course-player/sequence-container/SequenceContainer.scss
src/features/footer/Footer.scss

Fix footer styles to more closely match Figma.
Also fix horizontal overflow on sequence container in mobile.
```diff
```

fix(DEX-4215): Fix footer styles to more closely match figma

---

src/features/course-player/sequence-container/SequenceContainer.scss

Fix h1 font size on mobile and desktop
```diff
```

fix(DEX-4161): Fix h1 font size on mobile and desktop

---

src/features/footer/Footer.scss
src/features/layout/Layout.scss

Show aria tooltip on keyboard focus, align footer content to course content.
```diff
```

fix(DEX-4148): Address observations

---

src/features/course-player/CoursePlayer.scss
src/features/course-view/CourseView.scss
src/features/layout/Layout.scss
src/variables.scss

Fix Scrollbar covering footer text and content on desktop when sidebar is minimized.
Also adjusted paddings when sidebar is extended that were broken after another change.
Formatted some scss files with Prettier.
```diff
```

fix(DEX-4354): Scrollbar covering footer text and content

---

src/features/course-player/sequence-container/SequenceContainer.scss
src/features/course-view/CourseView.scss
src/features/sidebar/Sidebar.jsx

Overview
https://projects.wgu.edu/browse/DEX-4224
- Conflicts resolved
- Add hover & focus to all interactive MFE elements (nav bar & buttons)
- Update colors to use Paragon vars
- Fix font weight on subsections
- Add width to "Previous" and "Next" so "Expand All" and "Collapse All" can use btn-outline-secondary class
- Add secondary class to nav utility buttons
Checklist
⚠️ Please make sure to fill this checklist before asking for reviews.
Code is correctly formatted and linted
Unit tests are updated and are passing
PR title follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary):
i.e. feat(CUR-###): Feature title
PR Title aligns to Semantic-Release [supported prefixes](https://www.conventionalcommits.org/en/v1.0.0/#examples) (NOTE: prefixes are case …

feat(DEX-4224)

---

src/features/course-view/CourseView.scss

Fix error on bookmark created by focus state.
```diff
```

Fix bookmark on focus

---

src/features/course-player/sequence-container/SequenceContainer.scss

Fix h2 font size breakpoint
```diff
```

fix(DEX-4161): Fix h2 font size breakpoint

---

docs/design/sidebar.md
src/components/Unit/Unit.jsx
src/features/header/Header.jsx

Add edx.ui.lms.outline.selected to the sidebar when navigating to another unit.
Update sidebar documentation to include changes.
```diff
```

feat(LER-1710): Add edx.ui.lms.outline.selected event to sidebar unit

---

src/features/course-player/sequence-container/SequenceContainer.jsx

Add check for course staff, if user is course staff display generate resource id button
```diff
```

feat(LER-1803): Show generate resource ids for course staff

---

.env.development
src/features/layout/Layout.jsx
src/index.jsx

[Please explain your changes and how to test them. Add screenshots if needed.]
```diff
feat(x) - Feature (0.X.0)
```

LER-18 Disable Footer Flag

---

README.md
src/components/Section/Section.jsx
src/components/Sequence/Sequence.jsx
src/features/resource-links/ResourceLinkGenerator.jsx

[Please explain your changes and how to test them. Add screenshots if needed.]
```diff
fix(x) - Patch (0.0.X)
```

Fix Errors and Warnings LER-1924

---

package-lock.json
package.json
src/components/Sequence/Sequence.jsx
src/components/Sequence/Sequence.test.jsx
src/features/course-player/CoursePlayer.jsx
src/features/course-player/sequence-container/SequenceContainer.jsx
src/features/course-player/sequence-container/SequenceContainer.scss
src/features/sidebar/Sidebar.jsx
src/features/sidebar/Sidebar.scss
src/index.jsx

- Add sidebar sequence lock for gated content
- Add test for sequence content lock in sidebar
- Sequence is clickable in sidebar if it does not contain any units
- Fix errors generated when the current unit id is not accessible
- Remove unit check from spinner
- Move AlertList to SequenceContainer
- Add styles for content lock
```diff
```

feat(LER-3238): Add lock for gated content
